### ISSUE TITLE
Fireworks when reaching a goal damage you

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#10]

**Comment by lifeofchrome** [comment]
There still seems to be an issue here: https://clips.twitch.tv/AcceptableSteamyDelicataRedCoat-kkITtCG9_japSGqM

**Comment by NeunEinser** [comment]
Seems like a different issue, since it generally doesn't happen anymore.

Feel free to open a new one. My guess is it's related to him standing on farmland. Other non-full blocks might be worth checking too.

Do you want to investigate or should I open the issue?

**Comment by lifeofchrome** [comment]
I suppose I'll look into it.
