### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#100]
* [player] joined [color] team
* Pregen chat messages ("Preparing Spawm...", "Loading Terrain")

**Comment by Kri5t0fK** [comment]
### Team joining
Currently in command blocks:
`tellraw @a ["", {"selector": "@p"}, " joined the blue team"]`

My suggestion for change:
1. Add translation for each `team display name` like (example for _blue_):
`"bingo.team_name.blue" : "Blue Team"`
2. Add translation for `team joining`:
`"bingo.lobby.team_join" : "%s joined the %s"`
3. Update command blocks with (example for _blue_):
`tellraw @a {"translate":"bingo.lobby.team_join","with":[{"selector":"@p"},{"translate":"bingo.team_name.blue"}]}`

### Pregen messages
Add translations for those lines:
- https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/game/start/locate_spawnpoint.mcfunction#L22
- https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/game/start/spawn_players.mcfunction#L8

_*also - the title of the issue should be "Untranslated", cause they ARE translatable ;)_

**Comment by Kri5t0fK** [comment]
One more untranslated text:
https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/game/start/start_game.mcfunction#L10

**Comment by Kri5t0fK** [comment]
Oh, I've found the `More setting coming soon` sign in code:
https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/lobby/set_signs.mcfunction#L66

**Comment by NeunEinser** [comment]
> My suggestion for change:
> 
>     1. Add translation for each `team display name` like (example for _blue_):
>        `"bingo.team_name.blue" : "Blue Team"`
> 
>     2. Add translation for `team joining`:
>        `"bingo.lobby.team_join" : "%s joined the %s"`

I think I'd prefer a separate string for each team join message (e.g. `%s joined the blue team.`). Usually stuff like this is better for languages were words change depending on context, so I like to stick to more specific strings as much as possible.

> **also - the title of the issue should be "Untranslated strings", cause they ARE translatable ;)*

Not sure how you mean it, but no they are not translatable. It is impossible to change them through language json files. An untranslated string would be a string missing from e.g. de_de.json.

> Oh, I've found the `More setting coming soon` sign in code:

Yeah not sure about this one. I originally planned to implement them before a 5.0 full release, so this sign was never meant to be there for long. But I guess by now it'd make sense to add that as well.

**Comment by Kri5t0fK** [comment]
> I think I'd prefer a separate string for each team join message (...) this is better for languages were words change depending on context

Oh yeah sure

> It is impossible to change them through language json files. An untranslated string would be a string missing from e.g. de_de.json (but present in en_us.json).

Ok, now I see what you meant here - that we cannot translate them to other languages, cause they are **hardcoded** `right now`
And previously I understood the _untranslatable_ as those, which we **cannot even translate** through lang-identifiers

**Comment by NeunEinser** [comment]
> Ok, now I see what you meant here - that we cannot translate them to other languages, cause they are **hardcoded** `right now`
And previously I understood the _untranslatable_ as those, which we **cannot even translate** through lang-identifiers

I fail to see the difference between the two statements. You cannot translate them through lang identifiers, that is true for these hardcoded texts - because they are hardcoded 😉

**Comment by Kri5t0fK** [comment]
Also, that's probably the best `RegEx` for search stripping to search for `tellraw` command that **doesn't** use `translate` 
_(assuming that entire command is translatable correctly when `translate` is used)_:
The RegEx: `/tellraw(?!.*translate).*/`

### Summarizing - lines with `hardcoded` text, that _should_ be translatable:
- [ ] "Preparing spawn..."
https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/game/start/locate_spawnpoint.mcfunction#L22
- [ ] "Loading terrain" https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/game/start/spawn_players.mcfunction#L8
- [ ] "GO!" https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/game/start/start_game.mcfunction#L10
- [ ] `sign`: "More setting coming soon..." + `click_events` https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/lobby/set_signs.mcfunction#L66
- [ ] "[ERROR] Could not find categories [...] of item [...]" https://github.com/NeunEinser/bingo/blob/1f1269b8e4aa06fad0aef13f1e9020c0dcfd3ced/data/bingo/functions/init/find_categories.mcfunction#L36
