### ISSUE TITLE
Switching gamemode is prevented even after getting a blackout

### ISSUE THREAD

**Issue by bl4ckscor3** [NeunEinser/bingo#104]
The system to prevent accidental gamemode switching is still in effect even after the player got a blackout (see screenshot). Since the player has nothing more to achieve after getting a blackout, it should be possible for them to switch gamemode without it being prevented.
![](https://i.imgur.com/ObSXsTB.png)

**Comment by NeunEinser** [comment]
Notes:
- Add tag `bingo.spectator` in `bingo:item_detection/goals/announce_blackout`
- Check team in `bingo:tick/handle_player_join` and if 25 items are gotten, add tag `bingo.spectator`

**Comment by Kri5t0fK** [comment]
- [ ] Maybe add another information in `tellraw` in [`bingo:item_detection/goals/announce_blackout`](https://github.com/NeunEinser/bingo/blob/ab81d8a7b8e91670556c261160d0afdfe052a82a/data/bingo/functions/item_detection/goals/announce_blackout.mcfunction) like
  > Note: From now on manual gamemode switching with shortcuts is enabled, so feel free to change to spectator mode and wander around.

  so that people know about it

**Comment by NeunEinser** [comment]
I don't see the necessity. It's something they are either gonna notice or not, and it's not a big deal if they don't.

**Comment by NeunEinser** [comment]
I guess I could put it into the tooltip explanation in the preferences. I just don't want to spam chat with even more info, when I can avoid it.
