### ISSUE TITLE
Saturation Effect is flickering in inventory while in lobby

### ISSUE THREAD

**Issue by RedstoneDubstep** [NeunEinser/bingo#105]
Since Bingo 5.0 Pre-Release 1, there is a flickering Saturation effect in the survival/adventure mode inventory while the player is in the lobby. This flickering can be irritating for some players when navigating in their inventory, and should thus be prevented, e.g. by increasing the amount of time the effect is active for.
Attached is an example of the flickering Saturation effect.

https://user-images.githubusercontent.com/42962686/148096067-241f3cef-6d85-47f6-8307-1398c0668937.mp4

**Comment by NeunEinser** [comment]
This was really confusing, since the time you specify for effects is usually in seconds, so 1 second should never cause such flickering.
But then there is https://bugs.mojang.com/browse/MC-19648 :D

**Comment by Kri5t0fK** [comment]
**Suggestion** - Just like during the game start:
1. Here (in skybox) are given **permanent** effects:
https://github.com/NeunEinser/bingo/blob/ab81d8a7b8e91670556c261160d0afdfe052a82a/data/bingo/functions/game/start/spawn_players.mcfunction#L18-L21
2. Than here (after the countdown) they are cleared:
https://github.com/NeunEinser/bingo/blob/ab81d8a7b8e91670556c261160d0afdfe052a82a/data/bingo/functions/game/start/start_game.mcfunction#L14

... it can be also changed here `1` -> `1000000` for effect to last for `**:**` (aka _permanent_; +without digits flickering):
https://github.com/NeunEinser/bingo/blob/ab81d8a7b8e91670556c261160d0afdfe052a82a/data/bingo/functions/lobby/player_tick.mcfunction#L8-L9

**Comment by NeunEinser** [comment]
... or I just increase the number to 2 and call it a day :D

**Comment by Kri5t0fK** [comment]
> ... it can be also changed here `1` -> `1000000` for effect to last for `**:**` 

Note that even with permanent effect, you won't need to **clear the effect** until next game starts (which is already done **after countdown**) 😉

**Comment by NeunEinser** [comment]
Either all effects are temporary or all effects are "permanent". The levitation effect in the same file can't be permanent without additional clear commands.

I also don't like it from a programming point of view, as the end of the countdown is not really related to leaving the lobby.
