### ISSUE TITLE
Make the resource pack check version-specific

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#108]
If someone uses the resource pack from a previous version, the resource pack check will falsely assume the player has the resource pack installed correctly, breaking some things.

**Comment by Kri5t0fK** [comment]
My suggestion:
- `language placeholder string`:
encode additional _version data_ in `lang placeholder string`?
eg. `bingo_5.0pre1`/`bingo5.0pre1` _(currently just `bingo`)_
- `DoNotTranslateThis` entity (Single Player auto-resourcepack-detection):
  - (A) force manual check - remove following line https://github.com/NeunEinser/bingo/blob/75f83b2e5bec7217a9fa58eb86121480eb412876/data/bingo/functions/tick/tick.mcfunction#L25
  - (B) add _version data_ to `DoNotTranslateThis` -> `DoNotTranslateThis_5.0pre1`/`DoNotTranslateThis_bingo5.0pre1`

**Comment by NeunEinser** [comment]
I'd probably just go for an incremental number (so start at 1, then 2 and so on).
Singleplayer difference is supposed to stay. It doesn't really matter that much for SP as the resourcepack is automatically applied through the world download, but Ig it doesn't hurt either.

**Comment by NeunEinser** [comment]
To elaborate a bit more, I actually wanted to make a separate technical string for this.

- `%1074992263$s%1$s` stays as is.
- Add another string like `%1074992263$s%3$s%1$s` which is checked 2nd. This way we can have 2 error messages, one for "you do not have the rp" and one for "you have the wrong version of the rp". `%3$s` is the version indicator in this case, I think 3 is the first number that's save to use. It's simpler to modify for future versions if it's not included in the encoded string
- Remove technical strings from language files other than en_us, so you only have to edit one file.

It should be sufficient to keep one `DoNotTranslateThis` string though, as it's only used for checking whether the player should be teleported immediately, so having the logic in the chat message should be sufficient.

**Comment by Kri5t0fK** [comment]
> (...) Singleplayer difference is supposed to stay. It doesn't really matter that much for SP as the `resourcepack is automatically applied through the world download`, but Ig it doesn't hurt either.

Right, `DoNotTranslateThis` can stay as it is

**Comment by Kri5t0fK** [comment]
I guess the _resourcepack-version check_ is just needed for release versions, so won't add it (for now) in the message with
> This is not a release version (...)

Also, won't add the _version check_ to the `sign`, cause it would add another place to update the _version ID(iteraction)_
and it activates the check-message anyway.
