### ISSUE TITLE
Compatibility with Bedrock Client via Geyser

### ISSUE THREAD

**Issue by gunhippy** [NeunEinser/bingo#120]
Would it be possible to alter how things operate to make it so both bedrock and java players can exist in the same game. Current restrictions are:

Bedrock players cannot click signs
Resource Pack currently unavailable for bedrock players

**Comment by NeunEinser** [comment]
The resource pack uses some font shenanigans, with negative spaces and such, which I doubt would work on a Bedrock client. I am not even sure Bedrock supports the action bar display slot.

I also do not wish to sacrifice UX that works nicely on Java for Bedrock clients.

I think the better approach here would be to make an entirely separate version for Bedrock. Personally, I am not currently interested in Bedrock development however.
