### ISSUE TITLE
"Switch to spectator mode" clickable in lobby

### ISSUE THREAD

**Issue by UnlucksMcGee** [NeunEinser/bingo#124]
Version: 5.0-pre2

If you generate a card, start a game and return back to the lobby, then you can still `/trigger bingo.spectator`.
This leads to other issues in the next game where after you teleport to `bingo:multi_noise` you'll be in spectator mode, so you don't fall down to the ground but instead, your spawn point is set up in the air.

I'm unsure exactly how it's happening.
In [bingo:util/go_to_lobby.mcfunction](https://github.com/NeunEinser/bingo/blob/41f1b869781a54e04c364f005883a3c000701778/data/bingo/functions/util/go_to_lobby.mcfunction#L13):
```mcfunction
scoreboard players reset @s bingo.spectator
```
But maybe the line in [bingo:game/player_tick.mcfunction](https://github.com/NeunEinser/bingo/blob/41f1b869781a54e04c364f005883a3c000701778/data/bingo/functions/game/player_tick.mcfunction#L11):
```mcfunction
scoreboard players enable @s[tag=!bingo.spectator] bingo.spectator
```
somehow runs after the reset command above runs?

**Comment by NeunEinser** [comment]
Could test by inserting 2 debug /say commands and see the order stuff is happening in.

**Comment by NeunEinser** [comment]
Actually, this is quite easily explained by this order

https://github.com/NeunEinser/bingo/blob/41f1b869781a54e04c364f005883a3c000701778/data/bingo/functions/game/player_tick.mcfunction#L9-L11
