### ISSUE TITLE
Enhance build script translation parsing

### ISSUE THREAD

**Issue by UnlucksMcGee** [NeunEinser/bingo#125]
Adding this here for reference.

- Allow the build script to ignore/remove comments within the translations' json, by interpreting it as jsonc?

- Enhance the build script to print warnings for missing translations. Also need a special pattern for ignored translation keys, to prevent warnings for technical strings.

**Comment by NeunEinser** [comment]
This doesn't make sense anymore since translations are handled by crowdin
