### ISSUE TITLE
Some animals have NoAI:1

### ISSUE THREAD

**Issue by slicedlime** [NeunEinser/bingo#129]
In pre-release 3, some animals have NoAI:1 even while playing the game.

Clip from my stream where all the chickens around spawn had no AI: https://clips.twitch.tv/HorribleKitschyAntelopeKappaRoss-vZRcn_ZeTSUMv84Y

Also ran into it with a group of cows in a later run.

**Comment by NeunEinser** [comment]
Until the next release, not automatically starting pre-generation after generating a card should work around this issue, although I suppose there is a chance this issue might occur even with this setting, though it should be rarer and never happened during my testing.
