### ISSUE TITLE
find a way to add credits to the translation. (feature request)

### ISSUE THREAD

**Issue by Lorenzo0310200** [NeunEinser/bingo#139]
for the moment it is difficult to add credits to translations unless someone writes it here. perhaps by opening the community section on Github? or something else.

however for the moment I am the author of the Italian translation (my name is LorenzoG03102000 in Minecraft).

**Comment by Lorenzo0310200** [comment]
https://crowdin.com/project/fetchr

**Comment by NeunEinser** [comment]
Yep, I'll look into this once it is clear which people will need to be credited ;)

**Comment by NeunEinser** [comment]
Yep, I will look into this once I am about to release and it is clear no new translators will need to be added ;)

**Comment by Lorenzo0310200** [comment]
ok

**Comment by NeunEinser** [comment]
Resolved in f39c1b529dc52e7dfb283d3c630ed443fd5841c7
