### ISSUE TITLE
Italian translation bug list (to be fixed)

### ISSUE THREAD

**Issue by Loweredgames** [NeunEinser/bingo#142]
_this is a list of bugs I need to fix in translation: https://crowdin.com/project/fetchr/it_

- [x] la traduzione e spezzata e errata
![2022-07-20_11 18 29](https://user-images.githubusercontent.com/55211569/179946589-6e474c82-5b4d-4ae4-ae18-b60b42e663c2.png)

- [x]  la traduzione è errata
![2022-07-20_11 18 47](https://user-images.githubusercontent.com/55211569/179947094-53b2e730-7511-4b6c-a254-7e86c1684593.png)

- [x] la traduzione e spezzata e errata
![2022-07-20_11 19 06](https://user-images.githubusercontent.com/55211569/179947402-20296087-3f86-4e84-8eac-5561bfcff2bc.png)

**Comment by Lorenzo0310200** [comment]
OK created a new discussion in Crowdin.
