### ISSUE TITLE
Wrong game mode in lobby

### ISSUE THREAD

**Issue by gunhippy** [NeunEinser/bingo#147]
When returning to the lobby after a game, players are in survival and not adventure mode. This means they can break things. Ideal behaviour would be to return to adventure mode upon triggering the lobby.

**Comment by NeunEinser** [comment]
Hello and thanks for the feedback.

Currently you can use the red sign to switch players in the lobby to adventure mode. This however also means that they won't be able to interact with signs when they are not an operator.

In the next version, there will be separate settings for this and for servers, adventure mode will be the default on servers.
