### ISSUE TITLE
Bingo card shifts when item collected

### ISSUE THREAD

**Issue by gunhippy** [NeunEinser/bingo#149]
Version is 5.0.1 pre-release

Every time a player gets an item, the icons shift to the left and the board shifts to the right.

![image](https://user-images.githubusercontent.com/46465145/190930521-5da5266f-88a0-4a47-b473-3c2ea1c8087e.png)

![image](https://user-images.githubusercontent.com/46465145/190930526-4e00dd81-29d8-4c3a-807d-15870aa586a4.png)

![image](https://user-images.githubusercontent.com/46465145/190930530-fd71fd08-fc52-466a-8415-e762711baaaa.png)

**Comment by NeunEinser** [comment]
I cannot reproduce this.

Can you send me the world file?

**Comment by NeunEinser** [comment]
Or one idea I have, but I can't verify that it would cause this right now - is it possible that you switched teams after the match had already started?

That's not supported in many ways.

**Comment by gunhippy** [comment]
That's a possibility actually. The first time we tested it did it so we dropped back to lobby. I reset the server with a fresh instance and we tried again, but we realised after hitting go out teams were wrong.

However it did happen the first test.

Is it possible that it's an issue when more than 1 player plays?

**Comment by gunhippy** [comment]
Can confirm that it does not seem to be an issue in single player, even with switching teams during generation. I'll get some victims and test multiplayer later

**Comment by NeunEinser** [comment]
During pre-generation is fine, it's after you leave the lobby when it becomes an issue.

**Comment by NeunEinser** [comment]
@gunhippy Okay, I finally got to check this.

You were absolutely correct - I broke the team initialization, so as soon as you had multiple teams, things are broken in pre1.

**Comment by NeunEinser** [comment]
Thank you for the report :) <3
