### ISSUE TITLE
LAN Issue on 5.1-beta - Not Recognizing Resource Pack

### ISSUE THREAD

**Issue by jbish55** [NeunEinser/bingo#155]
Trying to play the latest beta versions on LAN, but the game doesn't recognize that the connecting player has loaded the resource pack. (It also warns the player that the resource pack was built for an older version of the game if that's any consequence.) Have tried this on 5.1 beta1 and beta2 with no success. Keep clicking "Re-check" but it never recognizes the pack being there. Both players on latest version of 1.19.3. Can play 5.0.1 on LAN with no issues, so not a LAN issue itself.

Thank you!

**Comment by knirch** [comment]
mcfunction is unbeknownst to me, so not sure you'll mess things up.. that said; this let's me test the beta on lan at least; `/trigger fetchr.resource_pack_check set 91`

**Comment by NeunEinser** [comment]
Yes, that workaround will work for now 😉
