### ISSUE TITLE
Respawn location incorrect when dying in-game

### ISSUE THREAD

**Issue by KayTheRiverKat** [NeunEinser/bingo#168]
If I die while in the bingo minigame, I do not respawn at the spawn point for that bingo card. I respawn elsewhere with the error regarding the point being blocked etc., and I begin suffocating. My only option is to return to lobby and I can't continue the selected bingo card.

**Comment by NeunEinser** [comment]
Cannot reproduce - I tried simply killing myself, moving far away from spawn, using /kill, going far away from spawn, setting my spawnpoint using a bed, and using /kill, all of which seemed to work as intended (you spawn at the original Bingo spawnpoint)

Could you provide more details or provide perhaps a world / seed where this is reproducible?

**Comment by NeunEinser** [comment]
Since there was no response within reasonable amount of time, I am closing this as cannot reproduce.

If someone else encounters this and is able to provide proper reproduction steps, feel free to leave a comment here or open a new issue.
