### ISSUE TITLE
Command block check error message is broken

### ISSUE THREAD

**Issue by smooreace** [NeunEinser/bingo#169]
Trying to get a server set up for the wife and a few of her friends. Seems simple enough....

Im using Amp, so a few things are a bit more convoluted than this, but essentially I have the following

Created a new instance and conned it in to using the _server.settings_ provided
Copied the folder **Fetchr-5.1-beta3** from the zip file of the same name to the Minecraft folder

Amp has added a ton of other garbage to _server.settins_, but Idont see anything that sets off any flags to me as to why things arent working.

```
#Minecraft server properties
#Fri Mar 31 16:20:03 CDT 2023
enable-jmx-monitoring=false
level-seed=91
rcon.port=25575
enable-command-block=false
gamemode=survival
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=Fetchr-5.1-beta3
motd=
query.port=25565
pvp=false
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=normal
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
max-players=10
use-native-transport=true
enable-status=true
online-mode=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
resource-pack-prompt={"text"\:"A resource pack is required to connect to this server.","color"\:"red"}
server-ip=ip.ip.ip.ip
allow-nether=false
server-port=25567
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=true
hide-online-players=false
resource-pack=
server-portv6=25568
entity-broadcast-range-percentage=100
simulation-distance=10
player-idle-timeout=15
rcon.password=
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=false
function-permission-level=4
initial-enabled-packs=vanilla
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=15
max-world-size=29999984
```

The issue is that once joined your in a poorly, if at all, lit room with a wall that states "Resource pack installed. Click here for chat"
When you click you get...
The resource pack was successfully enabled
Click here to go to the lobby
%1074992263$s%%1$s    <--- and this line repeats infinitely

There is no way to click as that last line spams chat

She IS able to play single player with the same instance, so the client is, as best I can guess, set up and running properly.

Any help would be greatly appreciated!

**Comment by UnlucksMcGee** [comment]
`enable-command-block` should be set to true

But perhaps double check everything else with the  [server.properties](https://github.com/NeunEinser/bingo/releases/download/5.1-beta3/server.properties)

**Comment by smooreace** [comment]
That resolved the chat spam,

`function-permission-level=4`

That was my other issue. Amp refused to let that setting remain. So every time I started the server it reverted from 2 to 4

working great now, thank you for the help. Even though it was pointing out the obvious.

**Comment by NeunEinser** [comment]
Function permission of 4 is fine too, it just can't be set to 1.

Reopening this issue because of the broken command block check.

It's intended to spam, but with a readable error message 😉
