### ISSUE TITLE
Add newline at the end of the provided `server.properties`

### ISSUE THREAD

**Issue by JPenuchot** [NeunEinser/bingo#176]
Hello,

This is really just a nice to have for server scripting and deployment. I've been working on a [Dockerfile](https://github.com/JPenuchot/minecraft-bingo-container) to deploy PaperMC servers with your datapack and had to troubleshoot why *some* config lines added using `echo 'some-config=some-value' >> server.properties` at the end of the config you provide were not active depending on the order I added them.

It's fixed on my side by adding a newline, but adding it at the end of the file would avoid that trouble to other folks who would like to fetch your config straight from the source to automatically deploy Fetchr servers.

Anyway, my friends and I had lots of fun playing your minigame. 
Thanks a lot for your work :)

Regards,
Jules

**Comment by NeunEinser** [comment]
Thanks for the feedback!

**Comment by NeunEinser** [comment]
Btw, paper is not supported and commonly breaks datapacks, so generally it's recommended to use a Fabric setup with Lithium

**Comment by JPenuchot** [comment]
I'll keep that in mind if I encounter any problem. Thanks for the memo :)
