### ISSUE TITLE
People's names should not be translated

### ISSUE THREAD

**Issue by Loweredgames** [NeunEinser/bingo#180]
in my opinion the names or the company "Microsoft" shouldn't be translated or there shouldn't be any translation.

**Comment by NeunEinser** [comment]
In general, company names shouldn't be translated.

In languages with different alphabets, they may be transliterated according to the company's policies.

**Comment by Loweredgames** [comment]
OK so that's a no. sorry if you need it again @NeunEinser but you can change the name of the Italian translation of the credits to "Loweredgames" instead of "Lorenzo03102000". that I had changed the username (I will never change it again).

**Comment by Loweredgames** [comment]
thanks

**Comment by NeunEinser** [comment]
> you can change the name of the Italian translation of the credits to "Loweredgames" instead of "Lorenzo03102000". that I had changed the username (I will never change it again).

Thanks, it's updated for the next version. I can change the name all the time, it's not a big deal at all ;)

**Comment by Loweredgames** [comment]
> > you can change the name of the Italian translation of the credits to "Loweredgames" instead of "Lorenzo03102000". that I had changed the username (I will never change it again).
> 
> Thanks, it's updated for the next version. I can change the name all the time, it's not a big deal at all ;)

ok 👍
