### ISSUE TITLE
Lockout mode can be started with all players on the same team

### ISSUE THREAD

**Issue by bl4ckscor3** [NeunEinser/bingo#184]
When lockout mode is active, a game can be started even though all players are on the same team. I would argue this is inconsistent behavior with singleplayer, as all players (there is only one in SP) are on the same team there as well and lockout mode is not accessible. Because of this, I feel like a game with lockout mode active should not be startable when there are not at least two teams containing a non-zero amount of players.

**Comment by NeunEinser** [comment]
The game internally disables lockout mode in that case and will behave as if it is disabled (and thus won't announce the lockout race winner at the same time as a blackout happens) 

Personally, I don't think it needs to be prevented.

**Comment by bl4ckscor3** [comment]
We didn't notice until after the game had started that the game randomly but us in the same team when starting the card, a simple note before starting the game could do the trick as well.

**Comment by NeunEinser** [comment]
There is a bug with the current random team selection, in that only about 50% of the teams are possible (every team that is assigned an uneven integer), except for orange, which is assigned 1, where the chance is 50% of picking that team...

The fix of that bug should make this much rarer (1%).
