### ISSUE TITLE
My Skyblock Map - question

### ISSUE THREAD

**Issue by Loweredgames** [NeunEinser/bingo#190]
hello @NeunEinser sorry if I write you here but I don't know where I can contact you.
I need help with my map and datapack. basically I would need a system that detects players (I have if there is a server) when I enter the world. but there are some problems:

1. the first problem is that I used scoreboards to manually "generate" islands or structures in the world. so I have to block (by setting -1 in all scores) in the various scores.
2. the second problem is that the map must work both in singleplayer and in multiplayer. so it's the datapack that needs to detects out if you're into singleplayer or multiplayer.
I tried to use some tags but it doesn't solve the second problem, I hope you help me and ask me anything that interests you. 
Thank you

**Comment by Loweredgames** [comment]
this is the affected function:
`

##Multiplayer Setup


execute as @a[gamemode=spectator,scores={multiplayer=1}] run gamemode survival @a
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_install -1
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_islands -1
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_id 14000
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_islands 1
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_islands 2
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_islands 3
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_large 1400
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_default 1400
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_small 1400
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a SkyblockCE_structures 14000
execute as @a[scores={multiplayer=1..}] run scoreboard players set @a PSN_OLD -1
execute as @a[scores={multiplayer=5}] run setblock 0 62 0 minecraft:black_concrete
execute as @a[scores={multiplayer=5}] run tp @s 0 65 0 0 0
execute as @a[scores={multiplayer=5}] run gamemode survival @s
execute as @a[scores={multiplayer=5}] run fill 0 63 0 0 64 0 minecraft:air destroy
execute as @a[scores={multiplayer=5}] run spawnpoint @s 0 63 0
execute as @a[scores={multiplayer=5}] run setworldspawn 0 63 0
execute as @a[scores={multiplayer=6..}] run scoreboard objectives remove multiplayer_popup
execute as @a[scores={multiplayer_popup=200}] run tellraw @a ["",{"translate":"skyblock_classic_edition.multiplayer.popup","italic":true},{"text":"\"Skyblock Classic Edition\\datapacks\\Skyblock Classic Edition\\data\\skyblock\\functions\\multiplayer.mcfunction\"","italic":true,"underlined":true,"clickEvent":{"action":"copy_to_clipboard","value":"\"Skyblock Classic Edition\\datapacks\\Skyblock Classic Edition\\data\\skyblock\\functions\\multiplayer.mcfunction\""}}]
execute as @a[scores={multiplayer_popup=5000000..}] run scoreboard players set @a multiplayer_popup 0


##Server or Multiplayer (Only activate if you are in multiplayer: here below)
#scoreboard objectives add multiplayer dummy`

**Comment by Loweredgames** [comment]
`#scoreboard objectives add multiplayer dummy`
must be manually removed otherwise the function does not work.

**Comment by NeunEinser** [comment]
Sorry, I don't really have time to look into your issue, nor is this supposed a place to ask for command help :)

I recommend the MinecraftCommands Discord, it's a great place to get help with all kinds of mapmaking problems: https://discord.gg/QAFXFtZ

**Comment by Loweredgames** [comment]
OK thanks anyway
