### ISSUE TITLE
Console spam and mobs all frozen

### ISSUE THREAD

**Issue by OwOchle** [NeunEinser/bingo#207]
While using the datapack :
Mobs are all frozen
Console is spammed by command output and can't find a way to disable it.

**Comment by NeunEinser** [comment]
What is being spammed?

**Comment by MoreOwO** [comment]
[23:33:46 INFO]: [@: Modified storage tmp.fetchr:item_detection]

**Comment by NeunEinser** [comment]
Command block output is disabled at the start, so my best guess is, you are not running vanilla.

Paper / Spigot is unsupported and breaks datapacks in many ways.

For the best performance, I recommend Fabric with Lithium.

If that's not the issue, which Minecraft version are you using?

**Comment by MoreOwO** [comment]
ooooh, that's why, i was just using paper, is it mentionned somewhere ?

**Comment by NeunEinser** [comment]
Yes, in bold letters at the installation instructions on both CurseForge and Modrinth :)
