### ISSUE TITLE
Please update the Chinese translation since I've finished it in crowdin

### ISSUE THREAD

**Issue by heerxingen** [NeunEinser/bingo#213]
I've finished the last 60% of the Chinese translation. Please update Fetchr's Chinese translation.
My crowdin account is named heerxingen and it's also my Minecraft ID.
<img width="1080" alt="image" src="https://github.com/NeunEinser/bingo/assets/102276349/ca507762-8c8d-456f-9388-79ccb8372ed9">
<img width="813" alt="image" src="https://github.com/NeunEinser/bingo/assets/102276349/67ec7692-bdc0-4807-b7fd-2bf4a5265722">

**Comment by NeunEinser** [comment]
Thank you for your contributions!

Crowdin automatically creates a pull request to this repository for any new contributions, in this case they were added to PR #212.

Translations are updated whenever a new version of Fetchr releases :)

**Comment by Steven-Jim** [comment]
great!
