### ISSUE TITLE
I've finished Korean translation.

### ISSUE THREAD

**Issue by stuned05** [NeunEinser/bingo#215]
I found this game yesterday and I wanted to play this game with my friends, who can't speak or read English.
Since I've just graduated my highschool and had nothing to do, I decided to translate this game into Korean.
My old ID is "stuned05" which is used in Crowdin and GitHub, and my current ID is "wx2htkd" which represents my Korean nickname, "쪼상".

![image](https://github.com/NeunEinser/bingo/assets/58105710/dcc0224f-2546-4e8f-862e-cf8d3f8e4e6e)

I hope you love my Korean translation. Thank you.

**Comment by NeunEinser** [comment]
Thank you very much!

This will be included in the next version, but there is currently no plans for a new version, so it will take some time until it's offcially released.

Meanwhile you can use this resource pack tho, which gives you korean translations (and nothing else, you still need the normal resource pack) if your friends need it: [Fetchr-5.1.1-korean.zip](https://github.com/NeunEinser/bingo/files/13592270/Fetchr-5.1.1-korean.zip)
