### ISSUE TITLE
Items not moving into inventory after a couple seconds

### ISSUE THREAD

**Issue by CJ5767** [NeunEinser/bingo#217]
My friend and I are trying to play bingo, but we've encountered this strange issue where we break blocks and we can collect them for maybe 5 seconds. After 5 seconds, the items do not move into our inventories. They don't freeze, still spin. I've attached a screenshot from the server console showing what I assume is the root of the error. Please let me know if this is fixable
![Screenshot (31 1)](https://github.com/NeunEinser/bingo/assets/162124680/ad341564-3a90-4b33-bea5-3186ad2e867f)

**Comment by davepusey** [comment]
Never seen that message(s) on my multiplayer server. What are you running, and what specs?

**Comment by NeunEinser** [comment]
@CJ5767 The behavior you describe is what happens on a Paper or Spigot server.

Unfortunately, these server brands alter vanilla behavior in a way that is not compatible with datapacks and thus, they are not supported.

You will need to use either a vanilla server, or the recommended setup for best performance by using a Fabric server with Lithium.

**Comment by CJ5767** [comment]
Thank you so much for the input, I switched server types and that fixed it.
