### ISSUE TITLE
Powered snow dirt block not working (5.1.2-pre1)

### ISSUE THREAD

**Issue by davepusey** [NeunEinser/bingo#221]
Only tested in 24w12a

Seed 33153 (from the recent weekly seeds)

No dirt block as expect from changes in commit 72ee2de

![2024-03-29_23 17 43](https://github.com/NeunEinser/bingo/assets/787745/7de4bb68-910c-47b9-ba83-ae74fefafcba)
![2024-03-29_23 18 44](https://github.com/NeunEinser/bingo/assets/787745/8d000635-37e4-4096-ac6c-88f7d92dc0cf)
![2024-03-29_23 19 17](https://github.com/NeunEinser/bingo/assets/787745/bcf68d15-d9ea-4108-b9af-22bea1b746ff)

**Comment by davepusey** [comment]
Still not fixed in 5.1.2-rc1 on 1.20.5-pre1

![2024-04-11_13 26 51](https://github.com/NeunEinser/bingo/assets/787745/2012ce16-aa43-46c2-9883-4c0d41ae5cfc)

**Comment by NeunEinser** [comment]
Have you checked the exact block types?

I replace powdered snoe an area around the spawn with snow blocks now, both for effectiveness to provide more save blocks, and for esthetics.

**Comment by NeunEinser** [comment]
Have you checked the exact block types?

I replace powdered snow an area around the spawn with snow blocks now, both for effectiveness to provide more save blocks, and for esthetics.

In your screenshot, it looks to me like normal snow and not powdered snow, but it's not easy to distinguish.

**Comment by davepusey** [comment]
Confirming fixed in 5.1.2-rc1 on 1.20.5-pre1

![2024-04-11_17 59 12](https://github.com/NeunEinser/bingo/assets/787745/d842d037-9361-4a7d-b85c-3a15618cf13c)
