### ISSUE TITLE
Item Frame uses old texture in HUD

### ISSUE THREAD

**Issue by bl4ckscor3** [NeunEinser/bingo#222]
On the left side of the image you can see the HUD bingo card with the old item frame texture. On the right is the actual item frame item which uses the correct (new) texture.
Tested in Minecraft 24w12a with Fetchr 5.1.2 Pre-Release 1 and seed 1758866993.

![](https://i.imgur.com/rAwXBwS.png)

**Comment by NeunEinser** [comment]
Do you know ehrn the texture changed?

**Comment by bl4ckscor3** [comment]
Looks like in Minecraft 1.18.

**Comment by davepusey** [comment]
To be honest, I can't tell the difference, but according to the wiki...
![image](https://github.com/NeunEinser/bingo/assets/787745/37afe882-9164-4a96-ac54-6a017e2bc9ec)

**Comment by NeunEinser** [comment]
Ah yeah nice, if it changed last before original 1.20, I can just apply it without any overlay shenanigans.

Thanks!

**Comment by davepusey** [comment]
According to https://minecraft.wiki/w/Item_Frame#History there have been zero changes to the Item Frame in 1.20
