### ISSUE TITLE
"points race" mode is not selecting the winner correctly? (5.1.2-pre1)

### ISSUE THREAD

**Issue by davepusey** [NeunEinser/bingo#223]
(5.1.2-pre1 on 1.20.4)

Twice during Phedran's stream today we used the "points race" mode, and both times it announced the wrong winner?

![image](https://github.com/NeunEinser/bingo/assets/787745/1866bcad-746c-4f69-8ac3-8f28ecff4bf4)

![image](https://github.com/NeunEinser/bingo/assets/787745/5da648f6-0dfa-474c-99b2-e1a762bc59c9)

**Comment by davepusey** [comment]
And for completeness, it was 3 teams of 1 player each.

**Comment by davepusey** [comment]
Game today with 5 teams of 1 player each.

Second place was announced as the winner.

I wonder if this is an off-by-1 error, like referencing [1] instead of [0] somewhere.

![image](https://github.com/NeunEinser/bingo/assets/787745/2e19cfdb-71a0-44ae-ba19-db3109d668ba)

**Comment by davepusey** [comment]
Second game got it right lol

![image](https://github.com/NeunEinser/bingo/assets/787745/12971027-8964-4579-810b-724e9e148666)

**Comment by NeunEinser** [comment]
Yeah, im pretty sure it's arbitrary. https://github.com/NeunEinser/bingo/blob/dd43f89cdf21a2a3482a8de952b799e0b5dfeea5/datapack/data/fetchr/functions/item_detection/goals/points/find_winners.mcfunction iterates over a temporary copy of the teams array, but in the calling function that temporary array is never actually copied/created.

So, I think it just grabs some garbage data from whatever team happens to have been operated on last, maybe it's the last team that got an item, or something.

I haven't had time to check if this fixes it, and it doesn't happen in singleplayer, but I think I might have ways to reproduce it still.

**Comment by davepusey** [comment]
Will test and provide feedback, pending next hosted multiplayer session with Phedran and her patrons.

**Comment by davepusey** [comment]
Three more rounds tonight with Phedran's patrons. Correct winner(s) selected every time. I consider this fixed.
