### ISSUE TITLE
Request: allow "points race" time duration to be adjusted whilst in skybox (5.1.2-pre1)

### ISSUE THREAD

**Issue by davepusey** [NeunEinser/bingo#224]
(5.1.2-pre1 on 1.20.4)

Request to allow "points race" time duration to be adjusted whilst in skybox.

Using the trigger command appears to have no effect once you're in the skybox.

When we play casual rounds with Phedran, I want to be able to set the timer duration to end on the top of the hour, when she takes her breaks, however I cannot know the exact duration required until right before we are ready to hit the Start Game sign, so need to be able to adjust it from the skybox.

**Comment by NeunEinser** [comment]
The trigger should be disabled when you go no the skybox, I forgot to do this, thanks for mentioning!

You can change the time without any problem during the skybox phase, by returning to the lobby.

Changing any settings in the skybox is not supported, and would not work cleanly (the trigger is only enabled when actually clicking the sign).
