### ISSUE TITLE
Revealing the card in blind mode causes faulty UI rendering

### ISSUE THREAD

**Issue by bl4ckscor3** [NeunEinser/bingo#240]
The Fetchr UI renders incorrectly when revealing the bingo card in blind mode.

**Steps to reproduce:**
1. Generate a new card, making sure that blind mode is on
2. Wait for pre-gen to end and start the game
3. Once the game has started, click "Reveal the Bingo Card"

**Observed:**
The UI does not show any items and is rendered incorrectly:
![2024-10-17_22-11-47](https://github.com/user-attachments/assets/eec178ec-aa5f-4588-8a77-9ae903a81993)

**Expected:**
The UI would correctly display all items and in the correct place.

**Comment by davepusey** [comment]
Confirmed. We just had it happen too during Phedran's stream today...
![image](https://github.com/user-attachments/assets/aa846239-a358-47dc-a817-8d830dbddf6d)

**Comment by davepusey** [comment]
Can be seen at https://www.twitch.tv/videos/2280092833?t=03h03m25s
