### ISSUE TITLE
Item counter in chat messages is off by one

### ISSUE THREAD

**Issue by bl4ckscor3** [NeunEinser/bingo#244]
In Fetchr 5.1.4 Beta 1, the item counter that is shown next to the time in chat messages when someone has gotten an item is off by one. The very first "player got item" message will show an outdated value from the previous game, then the second message will be shown as item 1, even though it is item 2.

Bug in action: https://www.youtube.com/watch?v=yw1E9pU-0ss&t=4770s

**Comment by NeunEinser** [comment]
The very first item in a completely new instance will also be shown as #<nothing> https://www.youtube.com/live/yw1E9pU-0ss

**Comment by kmpoppe** [comment]
Thanks for reporting this @bl4ckscor3, life got in the way of me getting it ready 🙄

K
