### ISSUE TITLE
Different pale forest item in card and board Fetchr 5.1.4 Pre-Release 2

### ISSUE THREAD

**Issue by CraftyJessJess** [NeunEinser/bingo#246]
I have just loaded my first card of the new version, and the pale forest item is different on the board compared to the card. On the board the item is creaking heart, however on the card it shows chiselled resin bricks. Photo attached for reference. 
![2024-11-21_11 58 39](https://github.com/user-attachments/assets/a5c8cf59-37b1-4015-8ab8-2089bdb992fe)

**Comment by CraftyJessJess** [comment]
Addition: The correct item for this card was creaking heart - using the /give player item function, chiselled resin bricks did not mark the item off the card, however, a creaking heart did

**Comment by CraftyJessJess** [comment]
Addition: Issue occurs consistently with these items on the board (creaking heart)/card (chiselled resin bricks) across different seeds. I am yet to find a card which contains a creaking heart item to test whether it accepts creaking heart or chiselled resin bricks as the item or shows correctly on the board.

**Comment by davepusey** [comment]
Can reproduce. HUD display shows wrong sprite when creaking heart is on the card.

![image](https://github.com/user-attachments/assets/ee5531ed-a6cb-4cac-a73f-f81be7f83678)
![image](https://github.com/user-attachments/assets/834e1ed2-842d-4d03-afe0-16b94e976549)

Suspect the sprites are inadvertently swapped between the two reported items. Currently looking for a seed with Chiseled Resin Bricks, to confirm this.

**Comment by davepusey** [comment]
Well, not exactly swapped. Perhaps an off-by-one error...?

![image](https://github.com/user-attachments/assets/7d30320b-b96e-47e6-bff0-5bf30f10e08e)

**Comment by davepusey** [comment]
![image](https://github.com/user-attachments/assets/f03ea265-24ac-4def-ab98-c682d4b15345)
