### ISSUE TITLE
Lockout Mode doesn't appear when opening a singleplayer world to LAN

### ISSUE THREAD

**Issue by iyloMC** [NeunEinser/bingo#252]
Title. I understand why single player worlds don't have lockout mode, but it would sure be convenient if there was a way to get the multiplayer lobby to generate in a LAN world, without needing to set up a whole separate server for it.

**Comment by NeunEinser** [comment]
If you open to LAN and another player joins your world, the lobby will also switch to multiplayer mode.

It's only not present in single player, when you are one player and not on a server.
