### ISSUE TITLE
Lobby scaffolding does not regenerate correctly if broken.

### ISSUE THREAD

**Issue by davepusey** [NeunEinser/bingo#254]
5.2-rc2 on 1.21.4

Breaking the new chest scaffolding in the lobby, and then exiting and reloading the world, it seems to try to regenerate it but instead you just get floating scaffolding items on the floor instead.

Before reload...
![2024-12-24_22 08 05](https://github.com/user-attachments/assets/c42bcfc5-0f30-4c53-8b0a-3835377601e9)

After reload...
![2024-12-24_22 08 25](https://github.com/user-attachments/assets/8fcea719-3baa-4d39-bbab-f711b53aa15f)

**Comment by davepusey** [comment]
Does seem to work tho if the bottom most blocks are in place, so maybe it's somehow reliant on them always existing...
![2024-12-24_22 11 00](https://github.com/user-attachments/assets/af95dea9-ebd4-4dde-bb30-02d6fa5f188c)
![2024-12-24_22 11 14](https://github.com/user-attachments/assets/523f7b09-876e-48cc-a78c-5dbc3d359300)

**Comment by NeunEinser** [comment]
Yes, this is true, the bottom scaffolding is part of the main structure and never broken by the game itself, so didn't account for players messing with it.

**Comment by NeunEinser** [comment]
Also in general, please don't put the version number in the title of reports. Issue titles should stay consistent, even when the bug isn't fixed in a future version, and wether the current version is affected should be reflected by wether the report is open or closed.

Having the version you reproduced in in the description is enough 😉

And thanks for the otherwise well written and well researched report! 💜

**Comment by davepusey** [comment]
Now (in rc3) it just doesn't attempt to regenerate at all if the bottom blocks are missing?

**Comment by NeunEinser** [comment]
Correct, also see changelog.

**Comment by NeunEinser** [comment]
Is there any reason this should behave differently? I see you changing the behavior in your fork to always regenerate. I intentionally didn't do that - if someone is annoyed by the scaffolding, I thought why not give the option to remove it?
