### ISSUE TITLE
Timer visually starts before the players can move

### ISSUE THREAD

**Issue by opl-** [NeunEinser/bingo#49]
The game timer currently starts counting down while the world isn't yet generated and players are in the lobby. It'd make more sense for it to start the moment players can start moving and breaking blocks.

**Comment by MalbaCato** [comment]
The timer is reset back to 0 the moment the game starts so this is irrelevant. Don't close the issue tho, as neun seems not to be tracking that this needs to be fixed, as the times should not be shown (or kept at 0) before the game starts.

**Comment by NeunEinser** [comment]
Do you mean the keeping progress of gametime which counts *up*?
That's being reset once the game starts, the counting during setup is a display bug (I do use a worldborder timer for a different purpose there and currently that's displayed there as well)

**Comment by NeunEinser** [comment]
I am just going to assume above is what you mean and this will be used to track that issue. If there is another bug, feel free to open another issue.

**Comment by opl-** [comment]
> The timer is reset back to 0 the moment the game starts so this is irrelevant.

I did not realize that, though it does make sense. Still, it was rather confusing to see it tick up. Feel free to rename the issue title to better describe what the intended behavior is.

**Comment by NeunEinser** [comment]
Fixed in 86ca12e716d7bdbdca05f9d754663d64424cbc99
