### ISSUE TITLE
Be better at documenting

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#5]
There is no documentation.
git gud

**Comment by Kri5t0fK** [comment]
lacking `@context` here
https://github.com/NeunEinser/bingo/blob/c8e309b98fc33dc671385dc00bd06afd7e90b175/data/bingo/functions/game/start/set_spawn.mcfunction#L1-L6

from here (`at @a[...`):
https://github.com/NeunEinser/bingo/blob/c8e309b98fc33dc671385dc00bd06afd7e90b175/data/bingo/functions/game/start/countdown.mcfunction#L9

**Comment by Kri5t0fK** [comment]
### Is `#bingo:post_register_items` the same thing as `#bingo:post_registration`?
- storage `bingo:items categories[].items` - mentions `#bingo:post_register_items`
https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L54-L56
- storage `bingo:registries` - mentions both:
https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L67-L69 https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L82-L84
- no declaration for `#bingo:post_register_items`
- `#bingo:post_registration` declaration:
https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L1119-L1128

**Comment by Kri5t0fK** [comment]
### Maybe add info that `bingo:items` are generated from `bingo:registries`?
https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L24-L25 https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L1131-L1146

**Comment by Kri5t0fK** [comment]
### Add more info about `strict mode` (description, _only used in MP_)
https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L908-L913

**Comment by Kri5t0fK** [comment]
### Maybe encapsulate `consts` in `#region consts`? https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L935-L947

**Comment by Kri5t0fK** [comment]
### Add declaration for `#bingo:fill_registries` https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L1111-L1117

**Comment by Kri5t0fK** [comment]
### Explain registration of own items (or delete line `5` if it's to be done somewhere else) https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/fill_registries.mcfunction#L1-L5

**Comment by NeunEinser** [comment]
> ### Add declaration for `#bingo:fill_registries`
> 
> https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L1111-L1117

Only tags that are not otherwise declared (through a file) are declared with `#declare`. Unfortunately DPH+/SPYglass/IMP does currently not support documentation for tags like that.

**Comment by NeunEinser** [comment]
> ### Is `#bingo:post_register_items` the same thing as `#bingo:post_registration`?
> 
>     * storage `bingo:items categories[].items` - mentions `#bingo:post_register_items`
>       https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L54-L56
> 
>     * storage `bingo:registries` - mentions both:
>       https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L67-L69
>        https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L82-L84
> 
>     * no declaration for `#bingo:post_register_items`
> 
>     * `#bingo:post_registration` declaration:
>       https://github.com/NeunEinser/bingo/blob/d8fc361a1e40047e983374fda57679d54dbb5df9/data/bingo/functions/init/init.mcfunction#L1119-L1128

I think `#bingo:post_register_items` is the old name when nothing else but items were registered.

**Comment by NeunEinser** [comment]
I think it's good enough now. No need to keep track of this issue anymore.
