### ISSUE TITLE
On a server with a server resource pack, the prompt will immediately close due to the teleport to the lobby dimension

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#52]
This could possibly be solved by adding a tiny platform in the overworld dimension to have people confirm they successfully enabled the resource pack.
This probably should only be done in a server enviornment. It should be straight forward to detect that by spawning an entity with its name set to one of the translation strings in Bingo. The server shouldn't know about resource packs and thus shouldn't resolve the string, while that will happen in single player. The entity can then be selected using a `@e[name=bingo.translation.string]`. If that selector finds it, either the resource pack is missing in single player, or we are in a server environment.

**Comment by gbegerow** [comment]
This would also help with local multiplayer (Open to LAN) where some players missing the resourcepack. In a LAN game every player has to download the resourcepack by themselves.
