### ISSUE TITLE
Firework damage on goal completion in certain scenarios

### ISSUE THREAD

**Issue by lifeofchrome** [NeunEinser/bingo#55]
While 3bb0f80bed081d67f70b15ab466b797d3d627012 fixed most issues with fireworks damaging you, in certain cases this can still happen. These are the current ways I know to cause firework damage:

- Standing on farmland, a slab, trapdoor, etc. in a 4 block high area (specifically ~4.18-4.93 blocks to the ceiling from feet level)
- Walking into the firework in a cave (e.g. walking and jumping (no sprint) eastwards in a cave)

I think the only way to truly fix this is to give the player resistance or something.

Edit: I tried adding
```
effect give @s resistance 1 10 true
```
as the first command in `bingo:item_detection/goals/completed_goal_effects` and that seems to mostly solve the problem.

**Comment by NeunEinser** [comment]
Relates to #10
