### ISSUE TITLE
The timer keeps running while the game is paused

### ISSUE THREAD

**Issue by TheRedstoneer** [NeunEinser/bingo#64]
The timer seems to update based on real-time, not ingame time. Because of this bug, the timer does not show the time spent ingame.

This happens in Singleplayer mode, latest dev version.
Steps to reproduce:

1. Start a game
2. Press ESC -> MC pauses, the timer visibly stops
3. wait a few seconds
4. Continue playing
5. After a second, the timer in the actionbar updates by the amount of real time elapsed in the pause menu.

**Comment by NeunEinser** [comment]
The timer uses real time, so this is working as intended.
I _might_ add an option to use in game time instead, and with 1.17 it will be possible to detect pauses properly in both scenarios.
