### ISSUE TITLE
The click action for returning to the lobby should appear more often

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#71]
Currently, it only shows at the very start of the game, when you complete a goal and since beta2 when you rejoin the game.

It should additionally show up when an opponent team completes a goal, and when you die.

Possibly it would also make sense to send the message on a timer periodically in order to further minimize players losing access to it or getting confused on how to return to the lobby.

**Comment by UnlucksMcGee** [comment]
One idea is perhaps to prefix the tellraw messages in chat with an exit symbol that has a hover/click event to return to the lobby.
Something like an arrow pointing to a door maybe?

e.g.
![image](https://user-images.githubusercontent.com/74118470/140070937-d29c2fe5-5348-4a65-bc7e-179f730201dd.png)

Pros: 
- shows up more often without adding additional spam to the chat.

Cons: 
- might not be often enough if there are a lot of users typing in chat?
- might not be immediately obvious to the user, unless it is explained to them beforehand.

**Comment by NeunEinser** [comment]
Item gets are quite frequent, so if many people are chatting, you should also expect more item gets, don't think that would be an issue.

I just think it's not obvious enough and it's not really in a place where you'd expect it.
It becomes even more convoluted when more actions get added such as entering spectator mode (#70).

**Comment by NeunEinser** [comment]
I like that idea.
I think I would still prefer to send the full message in some situations (Rejoining I don't see any other way since there is no message send then anyways), but I also think I'd prefer it after completing a goal since it's very common to use these options then.

The 3 bars should be added to the GO! message on game start and every item get message. If you have other places in mind as well, there might be other things I am not thinking about.
Also, not sure when the Hint: text should appear now. Currently it is intentionally only on game start to reduce chat clutter, but if it's player triggered, I guess it could just always be when you press the 3 bars (but not when the full message is send by default)

**Comment by Kri5t0fK** [comment]
Beside deciding where to show current `hint-lobby`, 
it'd be also good to add `hint-menu` (about using `≡`) that displays for sure for the rejoining players, game start _and maybe in other moments_
