### ISSUE TITLE
Trigger bingo.card_pos not reset on game start

### ISSUE THREAD

**Issue by UnlucksMcGee** [NeunEinser/bingo#77]
After joining a game, the trigger `bingo.card_pos` does not get reset, and therefore shows up in the tab list when typing /trigger
![image](https://user-images.githubusercontent.com/74118470/139845060-e8525796-17b3-49df-a3d6-b051a5423a22.png)
Is there a particular reason why you commented out the line in this [commit](https://github.com/NeunEinser/bingo/commit/0ec8cb9ba81e29a7b9226bc5293fbec61c52ac78#diff-bc36ce7b6e3a53e30af91ad1f2b19ef809774e267038f2581143bc466117c202R26)?
In my opinion, I think the user should only have access to that trigger in the lobby.

**Comment by NeunEinser** [comment]
The reason it is commented is bad implementation, basically.

The trigger is not only used to trigger it but it actually also stores the selected value. So resetting it would mean currently that the game forgets the user's set value to something that is undefined and it can't deal with properly.
The easy solution here would be to use the bingo.pref trigger in the menu and use card_pos as the storage.

I kind of want to look into incorporating the card into the hud components system as well though, which then would make the card_pos objective completely unnecessary.

The next release should have one of these fixes employed though, as triggering it by accident can have (and actually will have in most cases) bad side effects, most notably completely hiding the card. I just noticed this too late to solve it for the beta2 release, and it's an issue that was present in all previous versions.

**Comment by UnlucksMcGee** [comment]
One workaround is to `execute as @a run trigger bingo.card_pos add 0` which will effectively disable the trigger but it keeps its current score.

**Comment by NeunEinser** [comment]
Ohh, that's a clever way to disable a scoreboard!
