### ISSUE TITLE
Option to hide seed until returning to the lobby

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#83]
Basically to prevent stream backseaters, or possible speedrun verification rules.

**Comment by Kri5t0fK** [comment]
Additionally, maybe make it display `-` before the 1st game (seed generation), so that the icon isn't so alone
Thats how it looks now:
![image](https://user-images.githubusercontent.com/53398204/153636442-b4dd8e22-2347-4374-9488-d0f9d9909980.png)

**Comment by Kri5t0fK** [comment]
###### Method of hiding:
When using [1.], it just looks as if the `seed-component` was _turned off_, which may be confusing for some people.
That's why I personally prefer option [2.].

**Comment by NeunEinser** [comment]
Yeah, it'd also just act like a spacer when not hidden, which might be confusing as well when there's something above it
