### ISSUE TITLE
Options for Pregen

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#88]
Pregen should be rewritten to support setting minimum pregenerated chunks and turn it completely off.
While the card is generated but not started, the pregeneration should just continue even if the minimum is reached.

Perhaps a maximum setting as well, to prevent generating a lot of chunks when someone generates a card on a server and then leaves?

**Comment by Kri5t0fK** [comment]
I'd suggest remaking pre-gen path algorithm like that:
- `spiral` - so it starts from the center `0,0` and goes outwards how much we tell it
- `R_min` and `R_max` - radiuses
- matrix `MxM`, where: `M = 2*R + 1` _(e.g. `R=2` below -> `M=5`)_
- turn rules:
  - `A`: `x==z`
  - `B`: `x<0`, `x==-z`
  - `C`: `x>0`, `x==-z+1`
- stop rule `D`: 
  - Opt. 1.: `x==R`, `x==-z`
  - Opt. 2.: `iter>=M*M` - might be better when using `R_min` and `R_max`

![image](https://user-images.githubusercontent.com/53398204/154258201-847f8213-2c4c-4acc-abfa-2c9e22895c4f.png)

**Comment by Kri5t0fK** [comment]
> It _might_ be good to have a `width` > 1 to the spiral though

What do you mean by that _width_?

**Comment by NeunEinser** [comment]
Well, the width :P

I think it's easier think about it generating in  circles / squares, and definitely much easier to visualize
![Untitled](https://user-images.githubusercontent.com/12124394/154320464-c14218ff-5c73-4e93-ac32-bcbfad00b73c.png)

With the circle approach width 3 you essentially generate each colored squares as one unit, and the 3 chunks going away from the origin in one line in one step.

You could do something like that with a spiral too, but dunno how to deal with corners in that case (in the square approach you can just split the line in easy to handle rectangles of the same size) and it's harder to think about for me at least. And I also don't know how to draw it :D

**Comment by Kri5t0fK** [comment]
1. Minimum, maximum settings:
   - radius, diameter, sth else?
   - scale: 1=`1 chunk` or 1=width of `3 chunks`
2. Width - constant? (probably 3)
3. With _width_=3 (let's say) algorithm can treat 3x3 chunks as one `9chunk` - so just jumps 3 chunks in given direction.
    That way we already load more chunks near each other.
    - Meaning: `+`-load; `-`-unload; `A`,`B`,`C` - consecutive `9chunk`s
    - Option 1: `+A`, `-A`, `+B`, `-B`, `+C`, ... - unload immediately after load
    - Option 2: `+A`, `+B`, `-A`, `+C`, `-B`, ... - unload after next `9chunk` is loaded (add a `chasing` AS/coords)
    - Option 3: [as Option 2, but longer time till unloading] - `slower chasing`

I don't fully remember everything from [gnembon's chunkloading video](https://youtu.be/KnZ5nlQbFvo) in terms of `forceload` (not sure if he even showed it), but basically - does `forceload` _half-load_ chunks around itself?
What is your experience with the forceloading that it's better to load more at once near each other (why is it better)?

**Comment by NeunEinser** [comment]
Some old version only unloaded chunks once it was done.
Observations:
- First "line" of chunks was comparatively slow
- 2nd line and all following lines were faster

Now since chunks are immediately unloaded, you basically have the speed you had for line 1 for all lines.
