### ISSUE TITLE
You can spawn inside a ravine or a lava/water lake

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#89]
Currently, you can spawn inside a deep ravine or a lava/water lake

The reason for this is that the game currently only places a block of dirt if the block below the skybox at y=63 is water. If there is a water lake at a different level, or a ravine/lava lake, you can spawn inside of that.

I think it would be best to fix this by:
1. Replace any type of air below spawn at y=63 and below with dirt
2. Replace any type of liquid and cave air below spawn without y-level restriction with dirt
3. The logic for placing the barrier block drop chute should stay the same.

**Comment by Kri5t0fK** [comment]
With the ravine, it potentially makes more problems when you spawn on artificially placed block in the middle of ~11-wide ravine (with 5 blocks space on each side) you can make it without having blocks in inv.

We would need to check for topmost blocks at a radius to determine spawnpoint/make a bigger platform then just 1 block.

**Comment by NeunEinser** [comment]
Yeah, I was thinking to simply make it a pillar instead of a single block, so you can break blocks below and get dirt that way to escape if not possible otherwise. IIRC 1.11 bingo also used a pillar for water spawns.

**Comment by Kri5t0fK** [comment]
> Yeah, I was thinking to `simply make it a pillar` (...)

Do it like that (pillar) or do we still want to think?

**Comment by NeunEinser** [comment]
Should be fixed in a way that prevents this from happening too
https://clips.twitch.tv/PerfectRespectfulGoblinPastaThat-Kj1DEhU9BB4bE1eN

**Comment by NeunEinser** [comment]
I updated the description at the top to state my plan of fixing this.
