### ISSUE TITLE
Options for timer

### ISSUE THREAD

**Issue by NeunEinser** [NeunEinser/bingo#90]
In 1.17+, it should be possible to reliably detect pausing by detecting dependencies between scoreboard statistics `minecraft:total_world_time` and `minecraft:play_time`.
There are arguments to be made for both timing methods, so it makes sense to support an option for this.

Maybe also an option for in game time or real time? For timing, usually real time is preferred, though.

**Comment by DaNubCoding** [comment]
Find it very annoying that whenever I pause and leave to do something else the timer keeps going, please do implement this! Thank you :)
