### ISSUE TITLE
When launching for first and successive times the player falls out of the game to death.. 

### ISSUE THREAD

**Issue by LightningAussie** [NeunEinser/bingo#94]
I have been using the older version (bing 5.0 beta1) without this issue, but updated to latest revision now the player falls out of the world when the game starts... the lobby doesnt load.
![Screen Shot 2021-11-17 at 10 25 48 pm](https://user-images.githubusercontent.com/94533257/142191912-46627ffc-9156-4da9-813b-face87e6ce66.png)

**Comment by NeunEinser** [comment]
There are 2 things I know about that can cause this:

1. You are using the wrong Minecraft version (1.16.5 is the correct one)
2. You downloaded master. You can find the correct download over here: https://github.com/NeunEinser/bingo/releases/tag/5.0-beta2

**Comment by LightningAussie** [comment]
Was using correct 1.16.5 but used the download link you provided and that solved the issue thank you.
